#!/usr/bin/env node
// Compiles the contracts with solc 0.8.26 (npm solc-js, no native toolchain needed).
// Writes out/<Contract>.json (abi + bytecode) and out/standard-input.json (for Etherscan verification),
// and exports the ABIs to packages/shared/src/abi.ts.
// Also compiles Uniswap v4 PoolManager (out/v4/PoolManager.json) for the local chain only — on mainnet we use
// the canonical deployment.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const solc = require("solc");
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "out");
fs.mkdirSync(path.join(out, "v4"), { recursive: true });

const remaps = [
  ["v4-core/", "lib/v4-core/"],
  ["@openzeppelin/contracts/", "lib/openzeppelin-contracts/contracts/"],
  ["solmate/", "lib/v4-core/lib/solmate/"],
];

function resolve(p) {
  for (const [from, to] of remaps) if (p.startsWith(from)) return path.join(root, to + p.slice(from.length));
  return path.join(root, p);
}

function findImports(p) {
  try {
    return { contents: fs.readFileSync(resolve(p), "utf8") };
  } catch {
    return { error: "not found: " + p };
  }
}

function collect(dir) {
  return fs
    .readdirSync(path.join(root, dir), { recursive: true })
    .filter((f) => f.endsWith(".sol"))
    .map((f) => path.posix.join(dir, f.split(path.sep).join("/")));
}

function compile(sources, settings, label) {
  const input = {
    language: "Solidity",
    sources: Object.fromEntries(sources.map((s) => [s, { content: fs.readFileSync(resolve(s), "utf8") }])),
    settings: {
      evmVersion: "cancun",
      metadata: { bytecodeHash: "none" },
      outputSelection: { "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object", "evm.bytecode.linkReferences"] } },
      ...settings,
    },
  };
  const t = Date.now();
  const res = JSON.parse(solc.compile(JSON.stringify(input), { import: findImports }));
  const errors = (res.errors || []).filter((e) => e.severity === "error");
  for (const w of (res.errors || []).filter((e) => e.severity !== "error" && !String(e.sourceLocation?.file).startsWith("lib/")))
    console.warn(w.formattedMessage);
  if (errors.length) {
    for (const e of errors) console.error(e.formattedMessage);
    process.exit(1);
  }
  console.log(`compiled ${label} in ${((Date.now() - t) / 1000).toFixed(1)}s`);
  return { res, input };
}

// ── our contracts ──
const ours = collect("src");
const { res, input } = compile(ours, { optimizer: { enabled: true, runs: 200 }, viaIR: true }, "etheragents");
// keep only the sources actually used (input with resolved imports) for verification
const allSources = {};
for (const s of Object.keys(res.sources)) allSources[s] = { content: findImports(s).contents };
fs.writeFileSync(path.join(out, "standard-input.json"), JSON.stringify({ ...input, sources: allSources }, null, 2));

const wanted = ["AgentLaunchpad", "AgentFactory", "AgentVault", "AgentCoin", "CoinDeployer", "GraduationGuardHook", "Create2Deployer", "MockIdentityRegistry"];
const abis = {};
for (const [file, contracts] of Object.entries(res.contracts)) {
  if (!file.startsWith("src/")) continue;
  for (const [name, c] of Object.entries(contracts)) {
    if (!wanted.includes(name)) continue;
    const art = { contractName: name, sourceName: file, abi: c.abi, bytecode: "0x" + c.evm.bytecode.object, deployedBytecode: "0x" + c.evm.deployedBytecode.object };
    fs.writeFileSync(path.join(out, name + ".json"), JSON.stringify(art, null, 2));
    abis[name] = c.abi;
    const size = c.evm.deployedBytecode.object.length / 2;
    console.log(`  ${name.padEnd(22)} ${size} bytes${size > 24576 ? "  !! over EIP-170" : ""}`);
  }
}

// ── ABI export for the API and web app ──
const sharedAbi = path.resolve(root, "../packages/shared/src/abi.ts");
if (fs.existsSync(path.dirname(sharedAbi))) {
  const pick = ["AgentLaunchpad", "AgentFactory", "AgentVault", "AgentCoin"];
  let ts = "// Generated by contracts/scripts/compile.mjs — do not edit.\n";
  for (const n of pick) ts += `export const ${n[0].toLowerCase() + n.slice(1)}Abi = ${JSON.stringify(abis[n])} as const;\n`;
  fs.writeFileSync(sharedAbi, ts);
  console.log("wrote packages/shared/src/abi.ts");
}

// ── v4 PoolManager for local chains (cached) ──
const pmOut = path.join(out, "v4", "PoolManager.json");
if (!fs.existsSync(pmOut) || process.env.REBUILD_V4) {
  const { res: r4 } = compile(["v4-core/src/PoolManager.sol"], { optimizer: { enabled: true, runs: 44444444 }, viaIR: true }, "v4 PoolManager (local chain only)");
  const c = r4.contracts["v4-core/src/PoolManager.sol"].PoolManager;
  fs.writeFileSync(pmOut, JSON.stringify({ abi: c.abi, bytecode: "0x" + c.evm.bytecode.object }));
}
