#!/usr/bin/env node
// Deploys Etheragents. Usage:
//   NETWORK=local   node scripts/deploy.mjs           (hardhat node on 127.0.0.1:8545, default keys)
//   NETWORK=sepolia RPC_URL=… DEPLOYER_PRIVATE_KEY=0x… OPERATORS=0x… node scripts/deploy.mjs
//   NETWORK=mainnet RPC_URL=… DEPLOYER_PRIVATE_KEY=0x… ADMIN=0x… TREASURY=0x… OPERATORS=0x… CONFIRM_MAINNET=yes node scripts/deploy.mjs
// Optional: AGENT_FEE (ETH, default 0.002), COIN_FEE (ETH, default 0), START_MCAP / GRAD_MCAP (ETH, defaults
// 0.0707 / 3.8).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createPublicClient, createWalletClient, http, parseEther, formatEther } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { mainnet, sepolia, hardhat } from "viem/chains";
import { deployAll, curveParams, MAINNET, SEPOLIA } from "./lib/core.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const NETWORK = process.env.NETWORK || "local";
const chains = { local: hardhat, sepolia, mainnet };
const chain = chains[NETWORK];
if (!chain) throw new Error("NETWORK must be local, sepolia or mainnet");

// Hardhat's well-known dev keys (account #0 deployer, #1 operator). Never use them anywhere else.
const LOCAL_DEPLOYER = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const LOCAL_OPERATOR = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8";

const pk = process.env.DEPLOYER_PRIVATE_KEY || (NETWORK === "local" ? LOCAL_DEPLOYER : null);
if (!pk) throw new Error("DEPLOYER_PRIVATE_KEY is required");
const account = privateKeyToAccount(pk);
const rpc = process.env.RPC_URL || (NETWORK === "local" ? "http://127.0.0.1:8545" : null);
if (!rpc) throw new Error("RPC_URL is required");
if (NETWORK === "mainnet" && process.env.CONFIRM_MAINNET !== "yes") throw new Error("set CONFIRM_MAINNET=yes to deploy to mainnet");

const client = createPublicClient({ chain, transport: http(rpc) });
const wallet = createWalletClient({ chain, transport: http(rpc), account });
const operators = (process.env.OPERATORS || (NETWORK === "local" ? LOCAL_OPERATOR : "")).split(",").map((s) => s.trim()).filter(Boolean);
if (!operators.length) throw new Error("OPERATORS (comma-separated brain addresses) is required");

const known = NETWORK === "mainnet" ? MAINNET : NETWORK === "sepolia" ? SEPOLIA : {};
const curve = curveParams(Number(process.env.START_MCAP || 0.0707), Number(process.env.GRAD_MCAP || 3.8));

console.log(`Deploying Etheragents to ${NETWORK} (chain ${chain.id}) from ${account.address}`);
console.log(`  balance ${formatEther(await client.getBalance({ address: account.address }))} ETH`);
console.log(`  curve: start ${curve.startMcapEth} ETH mcap → graduate at ${curve.gradMcapEth} ETH mcap (raises ≈ ${curve.raiseEth.toFixed(3)} ETH)`);

const d = await deployAll({
  wallet,
  client,
  admin: process.env.ADMIN || account.address,
  treasury: process.env.TREASURY || process.env.ADMIN || account.address,
  operators,
  poolManager: known.poolManager,
  identityRegistry: known.identityRegistry,
  agentFee: parseEther(process.env.AGENT_FEE || "0.002"),
  coinFee: process.env.COIN_FEE ? parseEther(process.env.COIN_FEE) : 0n,
  curve,
  log: (m) => console.log("  " + m),
});
d.network = NETWORK;

fs.mkdirSync(path.join(root, "deployments"), { recursive: true });
fs.writeFileSync(path.join(root, "deployments", `${d.chainId}.json`), JSON.stringify(d, null, 2));
// address book for the API and the web app
const all = {};
for (const f of fs.readdirSync(path.join(root, "deployments")).filter((f) => f.endsWith(".json")))
  all[f.replace(".json", "")] = JSON.parse(fs.readFileSync(path.join(root, "deployments", f), "utf8"));
fs.writeFileSync(
  path.resolve(root, "../packages/shared/src/deployments.ts"),
  "// Generated by contracts/scripts/deploy.mjs — do not edit.\nexport const deploymentsData: Record<string, unknown> = " + JSON.stringify(all, null, 2) + ";\n",
);
console.log(`\nwrote contracts/deployments/${d.chainId}.json and packages/shared/src/deployments.ts`);
