// Generated by contracts/scripts/deploy.mjs — do not edit.
export const deploymentsData: Record<string, unknown> = {
  "1": {
    "chainId": 1,
    "curve": {
      "virtualEth": "72040329284316099",
      "virtualToken": "1018957981390609000000000000",
      "curveSupply": "879970980383262000000000000",
      "raiseEth": 0.45611027454360137,
      "startMcapEth": 0.0707,
      "gradMcapEth": 3.8
    },
    "poolManager": "0x000000000004444c5dc75cB358380D2e3dE08A90",
    "identityRegistry": "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432",
    "create2Deployer": "0x0367b14cf33a7420413407bbae51de80adc3148c",
    "launchpad": "0xe405ca9e2cb0802eca791df1ba63fc636e5ac063",
    "coinDeployer": "0xc8cdc0b83e0af0e6becbfda244cd0df162bdf0a8",
    "graduationHook": "0xf25eed1d9daf2864efa85e39a2e8fc962650e000",
    "factory": "0x91f1f4f178b302930772f390bcc8b2c020006c94",
    "vaultImplementation": "0x4F5f6E522D4eE1e16570dA312D56c4FF659aD61c",
    "brainFund": "0xF38CcAEc04de9990B555beBEfAd2A8e9DB197233",
    "team": "0xAee57E25877220c2e1F71af805cC7DDb45749FB1",
    "buyback": "0x1d9019c2a681245d6531b14f8cf345467c1097d0",
    "tokenRewards": "0xe551e9ccb8b7dcf6c19e0c729c6d74718d8fb204",
    "admin": "0xAee57E25877220c2e1F71af805cC7DDb45749FB1",
    "deployer": "0x7D0F241FB2d1bd7e243dB1f91Bd538e97EE8e432",
    "agentFee": "2000000000000000",
    "treasury": "0xAee57E25877220c2e1F71af805cC7DDb45749FB1",
    "operators": [
      "0x11AdBc6EeCE1D51AD859bBaB301e60E5fe8B5381"
    ],
    "deployedAt": "2026-10-08T10:00:14.448Z",
    "startBlock": 26146943,
    "network": "mainnet"
  },
  "31337": {
    "chainId": 31337,
    "curve": {
      "virtualEth": "72040329284316099",
      "virtualToken": "1018957981390609000000000000",
      "curveSupply": "879970980383262000000000000",
      "raiseEth": 0.45611027454360137,
      "startMcapEth": 0.0707,
      "gradMcapEth": 3.8
    },
    "poolManager": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    "identityRegistry": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    "create2Deployer": "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
    "launchpad": "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
    "coinDeployer": "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
    "graduationHook": "0x05e5a1be27a04361ee38b81edabfb4c56351a000",
    "factory": "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6",
    "vaultImplementation": "0x94099942864EA81cCF197E9D71ac53310b1468D8",
    "brainFund": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "team": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "buyback": "0xb7f8bc63bbcad18155201308c8f3540b07f84f5e",
    "tokenRewards": "0xa51c1fc2f0d1a1b8494ed1fe312d7c3a78ed91c0",
    "admin": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "deployer": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "agentFee": "2000000000000000",
    "treasury": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "operators": [
      "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    ],
    "deployedAt": "2026-10-07T22:38:04.364Z",
    "startBlock": 17,
    "network": "local"
  }
};
